`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2018/11/14 11:20:34
// Design Name: 
// Module Name: opu_array
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

module opu_array_fc1#(
	parameter		ARRAY_ROW_NUM	  	= 32'd400,											//阵列行数
	parameter		ARRAY_COLUMN_NUM  	= 32'd120,											//阵列列数
	parameter		AD_WIDTH  	 		= 32'd8,											//AD位宽
	parameter		WEIGHT_WIDTH	    = 32'd8,											//光输入权值的位宽
	parameter		AD_IGNORE_WIDTH		= 32'd9
)(	
	input 																	I_sys_clk,		//时钟信号
	input 																	I_rst_n,		//复位信号
	input			[ARRAY_ROW_NUM - 1:0]									I_vg,			//输入电信号
	input			[ARRAY_ROW_NUM*ARRAY_COLUMN_NUM*WEIGHT_WIDTH - 1:0]		I_pos_weight,	//输入正阵列权重
	input			[ARRAY_ROW_NUM*ARRAY_COLUMN_NUM*WEIGHT_WIDTH - 1:0]		I_neg_weight,	//输入负阵列权重
	output	reg		[ARRAY_COLUMN_NUM*AD_WIDTH - 1:0]						O_ad_pos_data,	//正权值阵列AD输出信号
	output	reg		[ARRAY_COLUMN_NUM*AD_WIDTH - 1:0]						O_ad_neg_data,	//负权值阵列AD输出信号
	output			[ARRAY_COLUMN_NUM - 1:0]								O_ad_pos_eoc,	//正权值阵列AD转换结束信号	
	output			[ARRAY_COLUMN_NUM - 1:0]								O_ad_neg_eoc	//负权值阵列AD转换结束信号	
    );
	
	parameter		MID_RESULT_WIDTH 	= 32'd17;											
	
	reg				[ARRAY_COLUMN_NUM*MID_RESULT_WIDTH - 1:0]				pos_mid_result;	//正权值阵列计算中间结果
	reg				[ARRAY_COLUMN_NUM*MID_RESULT_WIDTH - 1:0]				neg_mid_result;	//负权值阵列计算中间结果
	
	reg				[ARRAY_COLUMN_NUM - 1:0]						O_ad_pos_eoc_pre_delay;	//正权值阵列AD转换结束信号（延迟前）	
	reg				[ARRAY_COLUMN_NUM - 1:0]						O_ad_neg_eoc_pre_delay;	//负权值阵列AD转换结束信号（延迟前）	
	
	always @(posedge I_sys_clk)	begin
		if(!I_rst_n)
			begin
				O_ad_neg_eoc_pre_delay <= 0;
				O_ad_pos_eoc_pre_delay <= 0;
			end
		else
			begin
				O_ad_neg_eoc_pre_delay <= {ARRAY_COLUMN_NUM{1'd1}};
				O_ad_pos_eoc_pre_delay <= {ARRAY_COLUMN_NUM{1'd1}};
			end
	end

	generate
	genvar j1;
	for(j1 = 0;j1 < ARRAY_COLUMN_NUM;j1 = j1+1)	begin:Y_mid_result
		always @(posedge I_sys_clk)		begin
			if(!I_rst_n)
				begin
					pos_mid_result[(MID_RESULT_WIDTH*(j1+1)-1)-:MID_RESULT_WIDTH] <= 0;
					neg_mid_result[(MID_RESULT_WIDTH*(j1+1)-1)-:MID_RESULT_WIDTH] <= 0;
				end
			else	
				begin			
					pos_mid_result[(MID_RESULT_WIDTH*(j1+1)-1)-:MID_RESULT_WIDTH] <= 
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*0+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[0]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*1+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[1]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*2+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[2]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*3+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[3]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*4+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[4]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*5+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[5]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*6+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[6]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*7+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[7]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*8+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[8]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*9+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[9]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*10+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[10]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*11+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[11]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*12+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[12]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*13+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[13]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*14+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[14]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*15+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[15]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*16+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[16]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*17+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[17]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*18+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[18]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*19+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[19]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*20+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[20]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*21+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[21]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*22+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[22]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*23+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[23]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*24+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[24]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*25+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[25]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*26+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[26]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*27+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[27]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*28+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[28]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*29+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[29]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*30+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[30]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*31+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[31]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*32+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[32]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*33+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[33]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*34+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[34]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*35+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[35]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*36+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[36]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*37+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[37]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*38+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[38]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*39+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[39]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*40+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[40]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*41+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[41]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*42+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[42]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*43+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[43]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*44+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[44]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*45+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[45]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*46+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[46]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*47+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[47]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*48+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[48]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*49+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[49]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*50+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[50]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*51+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[51]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*52+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[52]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*53+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[53]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*54+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[54]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*55+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[55]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*56+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[56]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*57+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[57]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*58+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[58]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*59+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[59]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*60+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[60]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*61+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[61]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*62+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[62]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*63+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[63]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*64+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[64]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*65+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[65]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*66+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[66]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*67+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[67]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*68+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[68]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*69+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[69]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*70+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[70]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*71+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[71]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*72+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[72]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*73+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[73]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*74+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[74]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*75+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[75]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*76+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[76]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*77+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[77]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*78+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[78]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*79+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[79]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*80+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[80]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*81+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[81]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*82+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[82]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*83+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[83]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*84+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[84]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*85+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[85]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*86+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[86]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*87+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[87]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*88+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[88]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*89+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[89]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*90+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[90]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*91+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[91]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*92+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[92]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*93+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[93]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*94+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[94]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*95+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[95]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*96+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[96]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*97+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[97]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*98+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[98]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*99+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[99]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*100+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[100]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*100+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[100]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*101+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[101]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*102+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[102]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*103+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[103]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*104+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[104]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*105+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[105]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*106+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[106]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*107+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[107]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*108+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[108]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*109+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[109]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*110+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[110]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*111+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[111]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*112+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[112]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*113+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[113]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*114+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[114]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*115+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[115]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*116+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[116]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*117+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[117]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*118+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[118]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*119+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[119]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*120+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[120]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*121+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[121]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*122+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[122]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*123+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[123]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*124+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[124]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*125+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[125]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*126+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[126]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*127+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[127]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*128+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[128]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*129+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[129]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*130+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[130]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*131+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[131]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*132+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[132]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*133+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[133]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*134+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[134]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*135+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[135]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*136+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[136]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*137+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[137]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*138+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[138]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*139+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[139]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*140+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[140]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*141+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[141]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*142+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[142]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*143+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[143]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*144+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[144]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*145+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[145]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*146+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[146]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*147+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[147]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*148+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[148]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*149+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[149]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*150+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[150]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*151+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[151]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*152+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[152]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*153+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[153]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*154+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[154]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*155+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[155]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*156+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[156]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*157+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[157]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*158+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[158]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*159+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[159]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*160+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[160]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*161+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[161]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*162+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[162]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*163+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[163]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*164+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[164]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*165+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[165]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*166+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[166]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*167+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[167]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*168+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[168]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*169+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[169]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*170+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[170]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*171+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[171]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*172+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[172]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*173+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[173]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*174+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[174]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*175+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[175]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*176+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[176]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*177+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[177]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*178+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[178]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*179+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[179]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*180+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[180]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*181+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[181]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*182+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[182]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*183+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[183]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*184+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[184]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*185+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[185]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*186+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[186]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*187+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[187]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*188+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[188]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*189+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[189]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*190+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[190]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*191+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[191]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*192+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[192]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*193+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[193]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*194+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[194]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*195+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[195]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*196+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[196]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*197+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[197]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*198+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[198]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*199+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[199]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*200+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[200]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*201+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[201]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*202+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[202]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*203+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[203]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*204+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[204]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*205+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[205]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*206+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[206]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*207+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[207]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*208+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[208]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*209+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[209]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*210+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[210]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*211+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[211]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*212+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[212]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*213+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[213]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*214+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[214]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*215+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[215]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*216+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[216]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*217+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[217]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*218+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[218]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*219+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[219]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*220+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[220]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*221+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[221]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*222+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[222]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*223+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[223]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*224+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[224]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*225+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[225]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*226+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[226]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*227+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[227]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*228+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[228]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*229+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[229]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*230+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[230]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*231+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[231]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*232+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[232]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*233+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[233]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*234+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[234]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*235+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[235]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*236+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[236]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*237+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[237]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*238+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[238]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*239+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[239]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*240+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[240]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*241+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[241]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*242+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[242]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*243+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[243]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*244+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[244]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*245+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[245]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*246+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[246]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*247+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[247]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*248+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[248]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*249+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[249]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*250+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[250]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*251+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[251]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*252+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[252]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*253+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[253]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*254+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[254]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*255+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[255]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*256+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[256]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*257+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[257]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*258+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[258]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*259+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[259]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*260+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[260]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*261+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[261]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*262+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[262]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*263+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[263]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*264+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[264]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*265+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[265]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*266+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[266]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*267+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[267]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*268+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[268]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*269+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[269]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*270+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[270]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*271+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[271]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*272+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[272]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*273+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[273]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*274+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[274]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*275+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[275]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*276+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[276]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*277+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[277]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*278+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[278]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*279+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[279]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*280+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[280]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*281+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[281]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*282+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[282]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*283+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[283]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*284+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[284]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*285+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[285]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*286+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[286]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*287+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[287]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*288+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[288]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*289+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[289]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*290+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[290]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*291+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[291]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*292+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[292]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*293+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[293]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*294+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[294]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*295+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[295]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*296+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[296]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*297+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[297]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*298+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[298]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*299+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[299]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*300+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[300]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*301+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[301]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*302+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[302]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*303+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[303]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*304+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[304]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*305+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[305]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*306+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[306]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*307+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[307]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*308+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[308]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*309+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[309]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*310+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[310]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*311+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[311]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*312+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[312]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*313+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[313]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*314+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[314]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*315+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[315]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*316+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[316]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*317+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[317]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*318+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[318]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*319+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[319]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*320+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[320]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*321+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[321]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*322+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[322]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*323+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[323]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*324+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[324]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*325+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[325]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*326+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[326]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*327+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[327]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*328+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[328]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*329+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[329]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*330+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[330]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*331+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[331]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*332+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[332]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*333+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[333]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*334+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[334]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*335+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[335]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*336+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[336]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*337+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[337]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*338+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[338]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*339+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[339]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*340+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[340]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*341+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[341]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*342+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[342]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*343+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[343]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*344+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[344]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*345+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[345]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*346+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[346]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*347+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[347]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*348+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[348]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*349+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[349]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*350+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[350]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*351+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[351]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*352+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[352]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*353+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[353]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*354+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[354]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*355+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[355]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*356+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[356]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*357+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[357]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*358+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[358]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*359+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[359]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*360+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[360]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*361+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[361]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*362+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[362]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*363+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[363]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*364+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[364]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*365+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[365]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*366+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[366]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*367+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[367]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*368+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[368]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*369+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[369]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*370+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[370]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*371+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[371]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*372+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[372]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*373+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[373]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*374+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[374]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*375+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[375]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*376+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[376]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*377+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[377]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*378+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[378]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*379+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[379]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*380+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[380]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*381+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[381]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*382+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[382]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*383+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[383]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*384+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[384]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*385+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[385]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*386+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[386]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*387+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[387]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*388+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[388]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*389+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[389]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*390+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[390]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*391+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[391]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*392+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[392]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*393+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[393]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*394+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[394]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*395+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[395]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*396+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[396]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*397+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[397]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*398+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[398]+
						I_pos_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*399+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[399];
						
					neg_mid_result[(MID_RESULT_WIDTH*(j1+1)-1)-:MID_RESULT_WIDTH] <= 
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*0+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[0]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*1+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[1]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*2+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[2]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*3+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[3]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*4+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[4]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*5+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[5]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*6+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[6]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*7+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[7]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*8+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[8]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*9+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[9]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*10+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[10]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*11+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[11]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*12+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[12]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*13+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[13]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*14+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[14]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*15+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[15]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*16+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[16]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*17+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[17]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*18+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[18]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*19+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[19]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*20+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[20]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*21+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[21]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*22+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[22]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*23+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[23]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*24+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[24]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*25+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[25]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*26+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[26]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*27+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[27]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*28+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[28]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*29+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[29]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*30+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[30]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*31+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[31]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*32+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[32]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*33+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[33]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*34+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[34]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*35+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[35]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*36+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[36]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*37+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[37]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*38+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[38]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*39+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[39]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*40+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[40]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*41+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[41]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*42+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[42]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*43+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[43]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*44+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[44]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*45+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[45]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*46+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[46]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*47+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[47]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*48+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[48]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*49+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[49]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*50+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[50]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*51+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[51]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*52+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[52]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*53+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[53]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*54+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[54]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*55+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[55]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*56+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[56]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*57+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[57]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*58+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[58]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*59+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[59]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*60+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[60]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*61+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[61]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*62+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[62]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*63+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[63]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*64+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[64]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*65+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[65]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*66+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[66]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*67+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[67]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*68+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[68]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*69+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[69]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*70+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[70]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*71+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[71]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*72+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[72]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*73+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[73]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*74+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[74]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*75+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[75]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*76+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[76]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*77+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[77]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*78+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[78]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*79+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[79]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*80+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[80]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*81+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[81]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*82+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[82]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*83+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[83]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*84+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[84]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*85+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[85]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*86+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[86]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*87+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[87]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*88+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[88]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*89+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[89]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*90+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[90]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*91+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[91]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*92+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[92]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*93+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[93]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*94+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[94]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*95+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[95]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*96+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[96]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*97+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[97]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*98+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[98]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*99+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[99]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*100+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[100]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*100+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[100]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*101+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[101]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*102+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[102]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*103+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[103]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*104+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[104]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*105+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[105]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*106+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[106]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*107+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[107]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*108+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[108]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*109+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[109]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*110+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[110]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*111+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[111]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*112+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[112]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*113+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[113]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*114+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[114]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*115+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[115]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*116+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[116]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*117+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[117]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*118+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[118]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*119+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[119]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*120+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[120]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*121+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[121]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*122+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[122]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*123+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[123]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*124+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[124]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*125+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[125]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*126+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[126]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*127+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[127]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*128+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[128]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*129+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[129]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*130+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[130]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*131+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[131]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*132+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[132]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*133+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[133]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*134+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[134]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*135+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[135]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*136+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[136]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*137+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[137]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*138+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[138]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*139+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[139]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*140+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[140]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*141+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[141]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*142+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[142]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*143+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[143]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*144+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[144]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*145+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[145]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*146+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[146]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*147+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[147]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*148+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[148]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*149+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[149]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*150+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[150]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*151+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[151]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*152+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[152]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*153+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[153]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*154+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[154]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*155+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[155]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*156+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[156]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*157+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[157]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*158+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[158]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*159+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[159]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*160+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[160]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*161+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[161]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*162+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[162]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*163+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[163]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*164+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[164]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*165+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[165]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*166+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[166]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*167+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[167]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*168+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[168]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*169+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[169]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*170+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[170]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*171+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[171]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*172+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[172]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*173+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[173]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*174+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[174]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*175+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[175]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*176+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[176]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*177+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[177]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*178+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[178]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*179+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[179]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*180+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[180]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*181+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[181]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*182+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[182]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*183+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[183]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*184+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[184]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*185+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[185]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*186+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[186]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*187+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[187]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*188+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[188]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*189+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[189]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*190+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[190]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*191+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[191]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*192+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[192]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*193+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[193]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*194+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[194]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*195+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[195]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*196+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[196]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*197+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[197]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*198+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[198]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*199+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[199]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*200+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[200]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*201+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[201]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*202+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[202]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*203+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[203]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*204+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[204]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*205+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[205]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*206+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[206]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*207+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[207]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*208+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[208]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*209+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[209]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*210+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[210]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*211+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[211]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*212+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[212]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*213+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[213]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*214+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[214]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*215+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[215]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*216+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[216]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*217+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[217]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*218+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[218]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*219+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[219]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*220+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[220]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*221+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[221]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*222+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[222]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*223+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[223]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*224+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[224]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*225+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[225]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*226+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[226]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*227+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[227]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*228+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[228]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*229+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[229]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*230+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[230]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*231+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[231]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*232+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[232]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*233+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[233]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*234+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[234]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*235+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[235]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*236+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[236]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*237+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[237]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*238+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[238]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*239+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[239]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*240+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[240]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*241+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[241]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*242+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[242]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*243+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[243]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*244+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[244]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*245+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[245]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*246+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[246]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*247+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[247]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*248+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[248]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*249+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[249]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*250+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[250]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*251+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[251]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*252+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[252]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*253+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[253]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*254+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[254]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*255+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[255]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*256+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[256]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*257+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[257]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*258+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[258]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*259+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[259]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*260+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[260]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*261+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[261]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*262+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[262]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*263+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[263]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*264+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[264]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*265+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[265]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*266+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[266]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*267+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[267]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*268+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[268]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*269+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[269]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*270+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[270]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*271+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[271]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*272+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[272]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*273+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[273]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*274+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[274]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*275+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[275]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*276+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[276]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*277+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[277]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*278+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[278]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*279+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[279]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*280+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[280]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*281+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[281]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*282+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[282]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*283+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[283]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*284+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[284]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*285+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[285]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*286+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[286]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*287+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[287]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*288+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[288]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*289+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[289]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*290+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[290]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*291+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[291]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*292+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[292]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*293+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[293]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*294+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[294]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*295+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[295]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*296+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[296]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*297+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[297]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*298+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[298]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*299+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[299]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*300+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[300]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*301+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[301]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*302+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[302]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*303+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[303]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*304+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[304]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*305+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[305]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*306+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[306]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*307+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[307]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*308+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[308]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*309+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[309]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*310+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[310]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*311+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[311]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*312+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[312]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*313+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[313]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*314+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[314]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*315+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[315]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*316+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[316]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*317+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[317]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*318+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[318]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*319+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[319]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*320+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[320]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*321+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[321]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*322+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[322]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*323+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[323]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*324+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[324]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*325+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[325]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*326+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[326]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*327+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[327]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*328+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[328]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*329+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[329]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*330+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[330]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*331+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[331]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*332+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[332]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*333+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[333]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*334+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[334]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*335+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[335]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*336+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[336]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*337+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[337]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*338+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[338]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*339+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[339]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*340+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[340]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*341+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[341]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*342+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[342]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*343+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[343]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*344+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[344]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*345+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[345]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*346+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[346]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*347+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[347]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*348+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[348]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*349+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[349]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*350+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[350]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*351+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[351]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*352+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[352]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*353+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[353]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*354+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[354]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*355+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[355]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*356+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[356]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*357+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[357]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*358+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[358]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*359+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[359]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*360+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[360]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*361+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[361]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*362+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[362]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*363+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[363]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*364+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[364]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*365+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[365]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*366+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[366]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*367+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[367]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*368+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[368]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*369+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[369]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*370+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[370]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*371+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[371]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*372+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[372]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*373+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[373]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*374+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[374]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*375+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[375]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*376+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[376]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*377+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[377]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*378+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[378]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*379+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[379]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*380+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[380]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*381+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[381]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*382+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[382]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*383+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[383]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*384+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[384]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*385+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[385]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*386+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[386]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*387+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[387]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*388+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[388]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*389+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[389]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*390+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[390]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*391+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[391]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*392+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[392]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*393+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[393]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*394+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[394]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*395+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[395]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*396+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[396]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*397+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[397]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*398+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[398]+
						I_neg_weight[(ARRAY_COLUMN_NUM*WEIGHT_WIDTH*399+WEIGHT_WIDTH*(j1+1)-1)-:WEIGHT_WIDTH] *I_vg[399];
						
				end
		end
	end
	endgenerate
	
	generate
	genvar j2;
		for(j2 = 0;j2 < ARRAY_COLUMN_NUM;j2 = j2+1)	begin:ouput_reg
			always@(posedge I_sys_clk)begin
				O_ad_pos_data[AD_WIDTH*(j2+1)-1:AD_WIDTH*j2] <= pos_mid_result[MID_RESULT_WIDTH*(j2+1)-1:MID_RESULT_WIDTH*j2+AD_IGNORE_WIDTH];   //因为AD位数有限制，因此忽略其后三位用以计算
				O_ad_neg_data[AD_WIDTH*(j2+1)-1:AD_WIDTH*j2] <= neg_mid_result[MID_RESULT_WIDTH*(j2+1)-1:MID_RESULT_WIDTH*j2+AD_IGNORE_WIDTH];			
			end
		end
	endgenerate
	
	
	//延时模块
	delay_Mtime_Nbit #(.TIMES(3),.BITS(ARRAY_COLUMN_NUM))  u_delay_Mtime_Nbit1
	(
		.I_din (O_ad_pos_eoc_pre_delay),
		.I_clk (I_sys_clk),
		.O_dout(O_ad_pos_eoc)
	);
	
	delay_Mtime_Nbit #(.TIMES(3),.BITS(ARRAY_COLUMN_NUM))  u_delay_Mtime_Nbit2
	(
		.I_din (O_ad_pos_eoc_pre_delay),
		.I_clk (I_sys_clk),
		.O_dout(O_ad_neg_eoc)
	);
	
endmodule

