# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/project/OPU/OPU_VHDL/FC1/FC1.srcs/sources_1/ip/ram2_672_2/ram2_672_2.xci
# IP: The module: 'ram2_672_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/OPU/OPU_VHDL/FC1/FC1.srcs/sources_1/ip/ram2_672_2/ram2_672_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram2_672_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/project/OPU/OPU_VHDL/FC1/FC1.srcs/sources_1/ip/ram2_672_2/ram2_672_2.xci
# IP: The module: 'ram2_672_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/OPU/OPU_VHDL/FC1/FC1.srcs/sources_1/ip/ram2_672_2/ram2_672_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram2_672_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
